### ISSUE TITLE
Nedostupná cesta při UPLOAD vyhodí chybu klienta, ale vytvoří soubor na serveru i log o přidání

### ISSUE THREAD

**Issue by Bloc3k** [martin-nohava/kryzbu#13]
Client :

```
Traceback (most recent call last):
  File "T:\Dokumenty\Programování\Python\kryzbu\src\kryzbu.py", line 20, in <module>
    client.Client.upload(file)
  File "T:\Dokumenty\Programování\Python\kryzbu\src\client\client.py", line 37, in upload
    file_size = os.path.getsize(file_path)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/neplatna/cesta/k/souboru'
```

Opět je to FileNotFoundError, tentokrát však na straně klienta. Ne na straně serveru jako je tomu u #9

**Comment by Bloc3k** [comment]
Vyřešeno v 773786ad3064762ec68ad2d56fc0fb7ae3a87cbf
