### ISSUE TITLE
Požadavek na DOWNLOAD neexistujícího souboru shodí server

### ISSUE THREAD

**Issue by Bloc3k** [martin-nohava/kryzbu#9]
Server error:

````
Traceback (most recent call last):
  File "T:\Dokumenty\Programování\Python\kryzbu\src\kryzbu_server.py", line 11, in <module>
    server.Server.run()
  File "T:\Dokumenty\Programování\Python\kryzbu\src\server\server.py", line 38, in run
    Server.serve_file(file_name, conn)
  File "T:\Dokumenty\Programování\Python\kryzbu\src\server\server.py", line 71, in serve_file
    file_size = os.path.getsize(file_path)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'server\\_data\\files\\<unexisting_file>

**Comment by Bloc3k** [comment]
Stejný typ erroru nastane, když se pokusím stahnout soubor s mezerou ohraničený `'` a né `"`.  
uživatel se může pokusit takový soubor stáhnout neboť zatím se mu při zadání `kryzbu.py -l` vypíšou sobory v jednoduchých závorkách `'`.


Server error se souborem `'te st.txt'`:

```Traceback (most recent call last):
  File "T:\Dokumenty\Programování\Python\kryzbu\src\kryzbu_server.py", line 11, in <module>
    server.Server.run()
  File "T:\Dokumenty\Programování\Python\kryzbu\src\server\server.py", line 38, in run
    Server.serve_file(file_name, conn)
  File "T:\Dokumenty\Programování\Python\kryzbu\src\server\server.py", line 71, in serve_file
    file_size = os.path.getsize(file_path)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 2] The system cannot find the file specified: "server\\_data\\files\\'te"

**Comment by Kaspis123** [comment]
Jak se zbavit aspotrofů
strings = ['A', 'B', 'C']
>>> print('strings = [{}]'.format(', '.join(strings)))
strings = [A, B, C]

**Comment by Kaspis123** [comment]
strings = ['A', 'B', 'C']
>>> print('strings = [{}]'.format(', '.join(strings)))
strings = [A, B, C]

**Comment by Kaspis123** [comment]
strings = ['A', 'B', 'C']
print('strings = [{}]'.format(', '.join(strings)))
strings = [A, B, C]

**Comment by Kaspis123** [comment]
Fixnuto

**Comment by Bloc3k** [comment]
V jakém commitu je kód opravující tuto issue?

**Comment by Kaspis123** [comment]
Commit dodán
